package rpc

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/steveyegge/beads/internal/eventbus"
	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/internal/types"
)

func (s *Server) handleCreateWithDeps(req *Request) Response {
	var args CreateWithDepsArgs
	if err := json.Unmarshal(req.Args, &args); err != nil {
		return Response{
			Success: false,
			Error:   fmt.Sprintf("invalid create_with_deps args: %v", err),
		}
	}

	if len(args.Issues) == 0 {
		return Response{
			Success: false,
			Error:   "no issues to create",
		}
	}

	store := s.storage
	if store == nil {
		return Response{
			Success: false,
			Error:   "storage not available (global daemon deprecated - use local daemon instead with 'bd daemon' in your project)",
		}
	}

	ctx, cancel := s.reqCtx(req)
	defer cancel()
	actor := s.reqActor(req)

	// idMapping maps old IDs (from args) to new IDs (generated by storage)
	idMapping := make(map[string]string)

	err := store.RunInTransaction(ctx, func(tx storage.Transaction) error {
		// First pass: create all issues and build ID mapping
		for i, issueArg := range args.Issues {
			// Save the reference ID for mapping before creating issue
			// The passed ID is used as a reference for dependency mapping,
			// NOT as the actual issue ID (to avoid duplicate key errors)
			refID := issueArg.ID
			if refID == "" {
				refID = fmt.Sprintf("%d", i)
			}

			issue := &types.Issue{
				ID:                 "", // Let storage generate unique ID (gt-yklx63 fix)
				Title:              issueArg.Title,
				Description:        issueArg.Description,
				IssueType:          types.IssueType(issueArg.IssueType),
				Priority:           issueArg.Priority,
				Design:             issueArg.Design,
				AcceptanceCriteria: issueArg.AcceptanceCriteria,
				Assignee:           issueArg.Assignee,
				EstimatedMinutes:   issueArg.EstimatedMinutes,
				Ephemeral:          issueArg.Ephemeral,
				IDPrefix:           issueArg.IDPrefix,
				Status:             types.StatusOpen,
			}

			// Create the issue (storage generates unique ID)
			if err := tx.CreateIssue(ctx, issue, actor); err != nil {
				return fmt.Errorf("failed to create issue %d (%s): %w", i, issueArg.Title, err)
			}

			// Map reference ID to new generated ID
			idMapping[refID] = issue.ID

			// Add labels for this issue
			for _, label := range issueArg.Labels {
				if err := tx.AddLabel(ctx, issue.ID, label, actor); err != nil {
					return fmt.Errorf("failed to add label %s to issue %s: %w", label, issue.ID, err)
				}
			}
		}

		// Second pass: create all dependencies using the ID mapping
		for _, depArg := range args.Dependencies {
			// Resolve FromID - might be an old ID that needs mapping
			fromID := depArg.FromID
			if mappedID, ok := idMapping[fromID]; ok {
				fromID = mappedID
			}

			// Resolve ToID - might be an old ID that needs mapping, or an existing issue ID
			toID := depArg.ToID
			if mappedID, ok := idMapping[toID]; ok {
				toID = mappedID
			}

			// Validate that external dependency targets exist.
			// Dolt does not enforce FK constraints, so we must check
			// explicitly to prevent dangling references.
			if _, ok := idMapping[depArg.ToID]; !ok {
				// toID was not created in this batch - verify it exists
				existing, err := tx.GetIssue(ctx, toID)
				if err != nil {
					return fmt.Errorf("failed to verify dependency target %s: %w", toID, err)
				}
				if existing == nil {
					return fmt.Errorf("dependency target %s does not exist", toID)
				}
			}
			if _, ok := idMapping[depArg.FromID]; !ok {
				// fromID was not created in this batch - verify it exists
				existing, err := tx.GetIssue(ctx, fromID)
				if err != nil {
					return fmt.Errorf("failed to verify dependency source %s: %w", fromID, err)
				}
				if existing == nil {
					return fmt.Errorf("dependency source %s does not exist", fromID)
				}
			}

			dep := &types.Dependency{
				IssueID:     fromID,
				DependsOnID: toID,
				Type:        types.DependencyType(depArg.DepType),
			}

			if err := tx.AddDependency(ctx, dep, actor); err != nil {
				return fmt.Errorf("failed to add dependency %s -> %s (%s): %w",
					fromID, toID, depArg.DepType, err)
			}
		}

		return nil
	})

	if err != nil {
		return Response{
			Success: false,
			Error:   fmt.Sprintf("transaction failed: %v", err),
		}
	}

	// Emit mutation events for all created issues
	for _, newID := range idMapping {
		s.emitMutation(MutationCreate, newID, "", "")
	}

	result := CreateWithDepsResult{
		IDMapping: idMapping,
		Created:   len(args.Issues),
	}

	return jsonOK(result)
}

// handleCreateMolecule creates multiple issues and their dependencies atomically.
// This fixes FK violations that occur when creating issues and dependencies
// in separate operations, as dependencies may reference issues that don't exist yet.
// (bd-jjbl)
func (s *Server) handleCreateMolecule(req *Request) Response {
	var args CreateMoleculeArgs
	if err := json.Unmarshal(req.Args, &args); err != nil {
		return Response{
			Success: false,
			Error:   fmt.Sprintf("invalid create_molecule args: %v", err),
		}
	}

	// Validate we have at least one issue
	if len(args.Issues) == 0 {
		return Response{
			Success: false,
			Error:   "at least one issue is required",
		}
	}

	store := s.storage
	if store == nil {
		return Response{
			Success: false,
			Error:   "storage not available",
		}
	}
	ctx, cancel := s.reqCtx(req)
	defer cancel()
	actor := s.reqActor(req)

	// Build ID mapping: template ID → new ID
	idMapping := make(map[string]string)

	// Use transaction for atomicity - this ensures all issues and dependencies
	// are created together, avoiding FK violations when dependencies reference
	// issues that haven't been created yet
	err := store.RunInTransaction(ctx, func(tx storage.Transaction) error {
		// First pass: create all issues with new IDs
		for _, spec := range args.Issues {
			// Build the issue from CreateArgs
			createArgs := spec.CreateArgs

			// Apply molecule-level defaults
			if args.Prefix != "" && createArgs.IDPrefix == "" {
				createArgs.IDPrefix = args.Prefix
			}
			if args.Ephemeral {
				createArgs.Ephemeral = true
			}

			// Parse optional fields
			var design, acceptance, notes, assignee, externalRef *string
			if createArgs.Design != "" {
				design = &createArgs.Design
			}
			if createArgs.AcceptanceCriteria != "" {
				acceptance = &createArgs.AcceptanceCriteria
			}
			if createArgs.Notes != "" {
				notes = &createArgs.Notes
			}
			if createArgs.Assignee != "" {
				assignee = &createArgs.Assignee
			}
			if createArgs.ExternalRef != "" {
				externalRef = &createArgs.ExternalRef
			}

			// Parse DueAt if provided
			var dueAt *time.Time
			if createArgs.DueAt != "" {
				if t, err := time.ParseInLocation("2006-01-02", createArgs.DueAt, time.Local); err == nil {
					dueAt = &t
				} else if t, err := time.Parse(time.RFC3339, createArgs.DueAt); err == nil {
					dueAt = &t
				} else {
					return fmt.Errorf("invalid due_at format %q for template %s", createArgs.DueAt, spec.TemplateID)
				}
			}

			// Parse DeferUntil if provided
			var deferUntil *time.Time
			if createArgs.DeferUntil != "" {
				if t, err := time.ParseInLocation("2006-01-02", createArgs.DeferUntil, time.Local); err == nil {
					deferUntil = &t
				} else if t, err := time.Parse(time.RFC3339, createArgs.DeferUntil); err == nil {
					deferUntil = &t
				} else {
					return fmt.Errorf("invalid defer_until format %q for template %s", createArgs.DeferUntil, spec.TemplateID)
				}
			}

			issue := &types.Issue{
				ID:                 createArgs.ID, // May be empty - storage will generate
				Title:              createArgs.Title,
				Description:        createArgs.Description,
				IssueType:          types.IssueType(createArgs.IssueType),
				Priority:           createArgs.Priority,
				Design:             strValue(design),
				AcceptanceCriteria: strValue(acceptance),
				Notes:              strValue(notes),
				Assignee:           strValue(assignee),
				ExternalRef:        externalRef,
				EstimatedMinutes:   createArgs.EstimatedMinutes,
				Status:             types.StatusOpen,
				Sender:             createArgs.Sender,
				Ephemeral:          createArgs.Ephemeral,
				Pinned:             createArgs.Pinned,
				AutoClose:          createArgs.AutoClose,
				IDPrefix:           createArgs.IDPrefix,
				CreatedBy:          createArgs.CreatedBy,
				Owner:              createArgs.Owner,
				MolType:            types.MolType(createArgs.MolType),
				RoleType:           createArgs.RoleType,
				Rig:                createArgs.Rig,
				EventKind:          createArgs.EventCategory,
				Actor:              createArgs.EventActor,
				Target:             createArgs.EventTarget,
				Payload:            createArgs.EventPayload,
				DueAt:              dueAt,
				DeferUntil:         deferUntil,
				AwaitType:          createArgs.AwaitType,
				AwaitID:            createArgs.AwaitID,
				Timeout:            createArgs.Timeout,
				Waiters:            createArgs.Waiters,
				CreatedAt:          time.Now(),
				UpdatedAt:          time.Now(),
			}

			if err := tx.CreateIssue(ctx, issue, actor); err != nil {
				return fmt.Errorf("failed to create issue for template %s: %w", spec.TemplateID, err)
			}

			// Store the mapping from template ID to the actual generated ID
			idMapping[spec.TemplateID] = issue.ID
		}

		// Second pass: create all dependencies using mapped IDs
		for _, dep := range args.Dependencies {
			fromID, ok1 := idMapping[dep.FromTemplateID]
			toID, ok2 := idMapping[dep.ToTemplateID]
			if !ok1 {
				return fmt.Errorf("unknown from_template_id: %s", dep.FromTemplateID)
			}
			if !ok2 {
				return fmt.Errorf("unknown to_template_id: %s", dep.ToTemplateID)
			}

			newDep := &types.Dependency{
				IssueID:     fromID,
				DependsOnID: toID,
				Type:        types.DependencyType(dep.DepType),
			}
			if err := tx.AddDependency(ctx, newDep, actor); err != nil {
				return fmt.Errorf("failed to create dependency %s → %s: %w", fromID, toID, err)
			}
		}

		return nil
	})

	if err != nil {
		return Response{
			Success: false,
			Error:   fmt.Sprintf("failed to create molecule: %v", err),
		}
	}

	// Determine root ID if RootTemplate was specified
	rootID := ""
	if args.RootTemplate != "" {
		rootID = idMapping[args.RootTemplate]
	}

	result := CreateMoleculeResult{
		IDMapping: idMapping,
		RootID:    rootID,
		Created:   len(args.Issues),
	}

	// Emit OjJobCreated event (bd-2iae)
	if rootID != "" {
		s.emitOjEvent(eventbus.EventOjJobCreated, eventbus.OjJobEventPayload{
			JobID:  rootID,
			BeadID: rootID,
		}, s.reqActor(req))
	}

	return jsonOK(result)
}

// handleCreateConvoyWithTracking creates a convoy issue and tracking dependencies atomically.
// This ensures the convoy and all tracking relations are created in a single transaction,
// preventing partial state where the convoy exists but some tracking deps failed.
func (s *Server) handleCreateConvoyWithTracking(req *Request) Response {
	var args CreateConvoyWithTrackingArgs
	if err := json.Unmarshal(req.Args, &args); err != nil {
		return Response{
			Success: false,
			Error:   fmt.Sprintf("invalid create_convoy_with_tracking args: %v", err),
		}
	}

	// Validate required fields
	if args.Name == "" {
		return Response{
			Success: false,
			Error:   "convoy name is required",
		}
	}

	if len(args.TrackedIssues) == 0 {
		return Response{
			Success: false,
			Error:   "at least one tracked issue is required",
		}
	}

	store := s.storage
	if store == nil {
		return Response{
			Success: false,
			Error:   "storage not available (global daemon deprecated - use local daemon instead with 'bd daemon' in your project)",
		}
	}

	ctx, cancel := s.reqCtx(req)
	defer cancel()
	actor := s.reqActor(req)

	var convoyID string
	trackedIDs := make([]string, 0, len(args.TrackedIssues))

	err := store.RunInTransaction(ctx, func(tx storage.Transaction) error {
		// Create the convoy issue
		convoy := &types.Issue{
			ID:        args.ConvoyID, // Will be auto-generated if empty
			Title:     args.Name,
			IssueType: types.IssueType("convoy"),
			Status:    types.StatusOpen,
			Owner:     args.Owner,
		}

		// Add notify address to description if provided
		if args.NotifyAddress != "" {
			convoy.Description = fmt.Sprintf("Notify: %s", args.NotifyAddress)
		}

		if err := tx.CreateIssue(ctx, convoy, actor); err != nil {
			return fmt.Errorf("failed to create convoy issue: %w", err)
		}
		convoyID = convoy.ID

		// Add tracking dependencies for each tracked issue.
		// Validate that each tracked issue exists first; Dolt does not
		// enforce FK constraints so we check explicitly.
		for _, trackedID := range args.TrackedIssues {
			existing, err := tx.GetIssue(ctx, trackedID)
			if err != nil {
				return fmt.Errorf("failed to verify tracked issue %s: %w", trackedID, err)
			}
			if existing == nil {
				return fmt.Errorf("tracked issue %s does not exist", trackedID)
			}

			dep := &types.Dependency{
				IssueID:     convoyID,
				DependsOnID: trackedID,
				Type:        types.DepTracks,
			}

			if err := tx.AddDependency(ctx, dep, actor); err != nil {
				return fmt.Errorf("failed to add tracking dependency for %s: %w", trackedID, err)
			}
			trackedIDs = append(trackedIDs, trackedID)
		}

		return nil
	})

	if err != nil {
		return Response{
			Success: false,
			Error:   fmt.Sprintf("transaction failed: %v", err),
		}
	}

	// Emit mutation event for convoy creation
	s.emitMutation(MutationCreate, convoyID, "", "")

	result := CreateConvoyWithTrackingResult{
		ConvoyID:     convoyID,
		TrackedCount: len(trackedIDs),
		TrackedIDs:   trackedIDs,
	}

	return jsonOK(result)
}

// handleAtomicClosureChain closes multiple related issues and updates an agent atomically.
// This is used for MR completion where we need to:
// 1. Close the MR bead with a reason (e.g., "merged")
// 2. Close the source issue with a reason
// 3. Optionally update the agent bead (e.g., clear hook_bead)
// All operations happen in a single transaction for consistency.
func (s *Server) handleAtomicClosureChain(req *Request) Response {
	var args AtomicClosureChainArgs
	if err := json.Unmarshal(req.Args, &args); err != nil {
		return Response{
			Success: false,
			Error:   fmt.Sprintf("invalid atomic_closure_chain args: %v", err),
		}
	}

	// Validate required fields
	if args.MRID == "" {
		return Response{
			Success: false,
			Error:   "mr_id is required",
		}
	}
	if args.SourceIssueID == "" {
		return Response{
			Success: false,
			Error:   "source_issue_id is required",
		}
	}

	store := s.storage
	if store == nil {
		return Response{
			Success: false,
			Error:   "storage not available",
		}
	}

	ctx, cancel := s.reqCtx(req)
	defer cancel()
	actor := s.reqActor(req)

	// Track results
	result := AtomicClosureChainResult{}

	err := store.RunInTransaction(ctx, func(tx storage.Transaction) error {
		// Step 1: Close the MR bead
		if err := tx.CloseIssue(ctx, args.MRID, args.MRCloseReason, actor, ""); err != nil {
			return fmt.Errorf("failed to close MR %s: %w", args.MRID, err)
		}
		result.MRClosed = true
		result.MRCloseTime = time.Now().Format(time.RFC3339)

		// Step 2: Close the source issue
		if err := tx.CloseIssue(ctx, args.SourceIssueID, args.SourceCloseReason, actor, ""); err != nil {
			return fmt.Errorf("failed to close source issue %s: %w", args.SourceIssueID, err)
		}
		result.SourceIssueClosed = true
		result.SourceCloseTime = time.Now().Format(time.RFC3339)

		// Step 3: Update agent bead if specified
		if args.AgentBeadID != "" && len(args.AgentUpdates) > 0 {
			if err := tx.UpdateIssue(ctx, args.AgentBeadID, args.AgentUpdates, actor); err != nil {
				return fmt.Errorf("failed to update agent %s: %w", args.AgentBeadID, err)
			}
			result.AgentUpdated = true
		}

		return nil
	})

	if err != nil {
		return Response{
			Success: false,
			Error:   fmt.Sprintf("transaction failed: %v", err),
		}
	}

	// Emit mutation events for the closures
	s.emitMutation(MutationStatus, args.MRID, "", "")
	s.emitMutation(MutationStatus, args.SourceIssueID, "", "")
	if result.AgentUpdated {
		s.emitMutation(MutationUpdate, args.AgentBeadID, "", "")
	}

	return jsonOK(result)
}
